---
title: "ML_output_fig"
author: "Steph Blain"
date: "2025-07-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(forcats)
library(scico)
library(cowplot)
library(ggpubr)
library(circlize)
library(geosphere)


theme_set(theme_classic())

shap1raw<-read_csv("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/rf_shap_dependence_data_202507.csv")
features1<-read_csv("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/univariate_permutation_with_quantiles.csv")
knn1<-read_csv("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/knn_imputed_full_dataset.csv")
interactions1<-read_csv("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/pairwise_permutation_with_quantiles.csv")

```

```{r}

renameFeatures1<-
  data.frame(Feature=c("release_year","fall_detectDay1","aims_heterozygosity",
                     "bodyCondition","sex_binary","fall_bearing1","kipps",
                     "tail.length","distal","releaseDay","wing.cord","p10",
                     "aims_ancestry","tarsus.length"),
           FeatureRenamed=c("Release year","Fall timing","Heterozygosity",
                     "Body condition","Sex","Fall orientation","Kipps (wing)",
                     "Tail length","Distal (wing)","Release day","Wing cord","p10 (feather)",
                     "Ancestry","Tarsus length"),
           FeatureCategory=c("Other","Behaviour","Genetics",
                     "Morphology","Other","Behaviour","Morphology",
                     "Morphology","Morphology","Behaviour","Morphology","Morphology",
                     "Genetics","Morphology"))

features1<-features1%>%left_join(renameFeatures1)

#get expected row count for remodeled df
ncol(shap1raw)/2*nrow(shap1raw)

shap1rows<-shap1raw%>%
  mutate(rowID=paste("row",1:nrow(shap1raw)))

shap1<-shap1rows%>%
  pivot_longer(!(starts_with("SHAP")|starts_with("rowID")),names_to="Feature",values_to="FeatureValue")%>%
  pivot_longer(starts_with("SHAP"),names_to="Feature2",values_to="SHAPValue")%>%
  mutate(Feature2=gsub("SHAP_","",Feature2))%>%
  filter(Feature==Feature2)%>%
  left_join(renameFeatures1)
shap1
nrow(shap1)
```

* verify that all features are unique & mean falls within quantiles
* extract traits with a feature importance greater than expected

```{r}

all(unique(features1$Feature)==features1$Feature)

all(features1$Mean_Delta_F1>features1$Q2.5&
      features1$Mean_Delta_F1<features1$Q97.5)

topFeatures<-features1%>%
  filter(Q2.5>0&Feature!="release_year")%>%
  pull(FeatureRenamed)

```

```{r}


gg1<-ggplot(features1,
       aes(x=Mean_Delta_F1,
           y=fct_reorder(FeatureRenamed,Mean_Delta_F1),
           colour=FeatureCategory))+
  #geom_bar(stat='identity')+
  geom_vline(xintercept=0,linetype=2)+
  geom_point(size=4)+
  geom_errorbar(aes(xmin=Q2.5,xmax=Q97.5),width=0.4,size=1.2)+
  scale_colour_manual(values=scico(4,palette='devon',categorical=F,end=0.8),
                    name='')+
  ylab('Trait')+xlab("\u0394 F1")+
  theme(legend.position = c(.8, .3))

gg1
```
```{r}
 #68 true negatives, 15 false positives, 19 false negatives, and 18 true positives

confusion1<-data.frame(TrueLabel=factor(c("Survived","Survived","Not survived","Not survived"),
                                        levels=c("Survived","Not survived")),
           PredictedLabel=factor(c("Survived","Not survived","Survived","Not survived"),
                                        levels=c("Not survived","Survived")),
           Count=c(18,19,15,68))

gg3<-ggplot(confusion1,aes(y=TrueLabel,x=PredictedLabel,fill=Count))+
  geom_tile()+
  geom_text(aes(label=Count))+
  scale_fill_scico(palette='davos',end=0.5,begin=0.2,guide='none',direction=-1)+
  coord_equal()+
  xlab("Predicted")+ylab("True")
gg3

```

```{r}
shap1topFeatures<-shap1%>%
  filter(FeatureRenamed%in%topFeatures[1:8])%>%
  mutate(FeatureRenamed=factor(FeatureRenamed,levels=topFeatures))%>%
  left_join(shap1rows%>%select(rowID,aims_ancestry))


gg2<-ggplot(shap1topFeatures,
       aes(x=FeatureValue,y=SHAPValue,colour=aims_ancestry))+
  geom_hline(yintercept=0,linetype=2)+
  geom_point(alpha=0.8)+
  facet_wrap(vars(FeatureRenamed),scales='free_x',nrow=2)+
  #scale_colour_manual(values=scico(4,palette='devon',categorical=F,end=0.88),
  #                    guide='none')+
  scale_colour_scico(palette='devon',end=0.7,guide='none',direction=-1)+
  ylab('SHAP value')+xlab('Trait value')

gg2
```

* SHAP sample size

```{r}

nrow(shap1)/length(unique(shap1$Feature))

```

```{r}


renameFeatures1<-
  data.frame(Feature=c("release_year","fall_detectDay1","aims_heterozygosity",
                       "bodyCondition","sex_binary","fall_bearing1","kipps",
                       "tail.length","distal","releaseDay","wing.cord","p10",
                       "aims_ancestry","tarsus.length"),
             FeatureRenamed=c("Release year","Timing","Heterozygosity",
                              "Body condition","Sex","Orientation","Kipps",
                              "Tail","Distal","Release\nday","Wing\ncord","p10",
                              "Ancestry","Tarsus"),
             FeatureCategory=c("Other","Behaviour","Genetics",
                               "Morphology","Other","Behaviour","Morphology",
                               "Morphology","Morphology","Behaviour","Morphology","Morphology",
                               "Genetics","Morphology"))

interactions2<-interactions1%>%
  filter(Q2.5>0)%>%
  left_join(renameFeatures1%>%
              mutate(Feature1=Feature,Feature1Renamed=FeatureRenamed)%>%
              select(Feature1,Feature1Renamed))%>%
  left_join(renameFeatures1%>%
              mutate(Feature2=Feature,Feature2Renamed=FeatureRenamed)%>%
              select(Feature2,Feature2Renamed))%>%
  select(Feature1Renamed,Feature2Renamed,Mean_Delta_F1)%>%
  arrange(-Mean_Delta_F1)

FeatureColours=scico(14,palette='devon',categorical=F,end=0.92)
names(FeatureColours)<-unique(c(interactions1$Feature1Renamed,
                                interactions1$Feature2Renamed))







chord1<-chordDiagram(interactions2,
                     grid.col=FeatureColours)

png("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/chord1.png",res=300,
    width=5,height=4,units='in')

chordDiagram(interactions2,
             grid.col=FeatureColours)

dev.off()


```


```{r}

chord2<-ggdraw() +
  draw_image("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/chord1.png")

chord2
```
```{r}

library(sf)
library(rnaturalearth)

meta1<-read.csv("~/GitHub_data/AIMs_metaData/AIMs_metadata.20250327.csv")
lat.df<-read.csv("~/GitHub_data/survivalData/motusDetections.filtered.20250409.csv")
data1<-read.csv("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/Dataset1.phiSurvival.20250707.csv")


#load map data
world <- ne_countries(scale = "medium", returnclass = "sf")

map1<-ggplot() +
  geom_sf(data = world,fill="grey90",colour=NA)+
  xlab("Longitude")+ylab("Latitude")+
  theme(panel.background = element_rect(fill='white'))+
  #theme(legend.position="none")+
  ylim(18,66)+xlim(-140,-55)
map1

```

* verify that orientation x ancestry x heterozygosity produces a unique combination per individual
* if yes, can be used for joining

```{r}

shap1raw%>%group_by(fall_bearing1,aims_ancestry,aims_heterozygosity)%>%
  summarise(count=n())%>%filter(count>1)%>%nrow()==0

bearingShap1<-data1%>%
  select(reference,name_in_vcf,fall_bearing1,aims_ancestry,aims_heterozygosity)%>%
  left_join(shap1raw%>%
              select(fall_bearing1,aims_ancestry,aims_heterozygosity,SHAP_fall_bearing1))%>%
  filter(!is.na(SHAP_fall_bearing1))

```

```{r}

projection<-"+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

lat.df.birds.fall1<-lat.df%>%
  filter(name_in_vcf%in%data1$name_in_vcf)%>%
  mutate(deployyear=as.numeric(substr(tagDeployStart,1,4)))%>%
  filter(detectyear==deployyear)%>%
  filter(detectdoy>212&tagProjID==280)%>%
  mutate(deployDay=substr(tagDeployStart,1,10),tsDay=substr(ts,1,10))%>%
  mutate(tagDays=as.integer(gsub(" days"," ",difftime(tsDay,deployDay,units="days"))))%>%
  select(motustagid,tsDay,tagDeployStart,tagDepLat,tagDepLon,
         recvDeployID,recvDeployLat,recvDeployLon,recvDeployName,
         detectyear,tagDays,detectdoy,deployDay,
         deployyear)%>%
  mutate(tagDeployStart=substr(tagDeployStart,1,10))%>%
  distinct%>%arrange(tagDays)%>%
  filter(!is.na(tagDays))%>%
  filter(motustagid!=85685)%>% #broken tag
  mutate(tagDepLat=if_else(motustagid%in%c(91383,85681),50.133366,tagDepLat),
         tagDepLon=if_else(motustagid%in%c(91383,85681),-122.95036,tagDepLon))

#estimate the distance between release site and detection site
#estimation needs to be pairwise, otherwise function will generate a matrix of all possible combos
lat.df.birds.fall1$releaseSiteDistance<-NA
for(i in 1:nrow(lat.df.birds.fall1)){
  lat.df.birds.fall1$releaseSiteDistance[i]<-
    distm(lat.df.birds.fall1[i,c("tagDepLon","tagDepLat")],
          lat.df.birds.fall1[i,c("recvDeployLon","recvDeployLat")],
          fun = distHaversine)
}

library(geosphere)

lat.df.birds.fall2<-lat.df.birds.fall1%>%
  filter(releaseSiteDistance<300000)%>%
    #keep the first record within the tier for each bird
    arrange(tagDays)%>%filter(!duplicated(motustagid))%>%
  mutate(motustagid=as.character(motustagid))%>%
  left_join(data1%>%
              mutate(motustagid=as.character(motustagid))%>%
              select(name_in_vcf,motustagid,aims_ancestry,aims_heterozygosity,phi_binary,fall_bearing1))
lat.df.birds.fall1

lat.df.birds.fall2<-lat.df.birds.fall2%>%
  dplyr::select(aims_ancestry,name_in_vcf,recvDeployLat,tagDepLat,fall_bearing1)%>%
  pivot_longer(c(tagDepLat,recvDeployLat),names_to='detect_type',values_to='latitude')%>%
  mutate(detect_type=gsub('Lat','',detect_type))%>%
  left_join(
    lat.df.birds.fall2%>%
      dplyr::select(name_in_vcf,recvDeployLon,tagDepLon)%>%
      pivot_longer(c(tagDepLon,recvDeployLon),names_to='detect_type',values_to='longitude')%>%
      mutate(detect_type=gsub('Lon','',detect_type)))

lat.df.birds.fall2<-lat.df.birds.fall2%>%
  left_join(bearingShap1%>%select(name_in_vcf,SHAP_fall_bearing1))%>%
  filter(!is.na(SHAP_fall_bearing1))

#write_csv(lat.df.birds.fall2,"C:/Users/Steph/TAMU_OneDrive/Thrushes/migratory_traits/fig2d_data.csv")

```

```{r,fig.width=5,fig.height=6}

mapOrient<-ggplot() +
  geom_sf(data = world,fill="grey95",colour='grey70')+
  geom_path(data=lat.df.birds.fall2,aes(x=longitude,y=latitude,
                                  group=name_in_vcf,colour=fall_bearing1),size=0.6,alpha=0.5)+
  #scale_colour_manual(values=natparks.pals("Banff")[c(4,1)])+
  geom_point(data=lat.df.birds.fall2,aes(x=longitude,y=latitude,
                                colour=fall_bearing1,group=name_in_vcf),size=1.5)+
  #scale_shape_manual(values=c(19,15,17))+
  
  scale_colour_gradientn(colours=scico(4,palette='davos',categorical=F,end=0.7,direction=-1),
                         name="Fall\norientation",values=c(0,0.25,0.75,1))+
  xlab("Longitude")+ylab("Latitude")+
  #theme(legend.position="none")+
  ylim(48,52)+xlim(-125,-118)
mapOrientMain<-ggplot() +
  geom_sf(data = world,fill="grey99",colour='grey70')+
  geom_path(data=lat.df.birds.fall2,aes(x=longitude,y=latitude,
                                  group=name_in_vcf,colour=SHAP_fall_bearing1),size=0.6,alpha=0.7)+
  #scale_colour_manual(values=natparks.pals("Banff")[c(4,1)])+
  geom_point(data=lat.df.birds.fall2,aes(x=longitude,y=latitude,
                                colour=SHAP_fall_bearing1,group=name_in_vcf),size=1.5,alpha=0.7)+
  #scale_shape_manual(values=c(19,15,17))+
  
  scale_colour_gradientn(colours=scico(4,palette='davos',categorical=F,end=0.9,direction=-1),
                         name="SHAP\nvalue",values=c(0,0.25,0.75,1))+
  xlab("Longitude")+ylab("Latitude")+
  #theme(legend.position="none")+
  ylim(48,52)+xlim(-125,-118)

insetMap1<-map1+theme_void()+
  geom_rect(aes(xmin=-125,xmax=-118,ymin=48,ymax=52),fill='grey30')+
  theme(panel.border = element_rect(colour = "grey30",fill=NA))

mapOrient<-ggdraw()+
  draw_plot(mapOrientMain)+
  draw_plot(insetMap1, x = 0.57, y = 0.71, width = 0.25, height=0.25)

```


```{r, fig.width=10,fig.height=15}

gg4=ggarrange(ggarrange(gg3,gg1,nrow=1,ncol=2,widths=c(0.7,1),labels=c("A","B")),
                      gg2,
              ggarrange(mapOrient,chord2,ncol=2,labels=c("D","E")),
              nrow=3,labels=c("","C"),heights=c(1,1.2,1))
gg4

ggsave("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/Fig2.pdf",
     plot=gg4,
     height = 12,width=10,bg='white')

ggsave("C:/Users/Steph/GitHub/thrush_hybrids/migratory_traits/Fig2.png",
       plot=gg4,dpi=1000,
       height = 12,width=10,bg='white')



```